#!/bin/bash

if [ -z $FRC_ROOT ]; then
    echo "FRC_ROOT environment variable not set, cowardly refusing to proceeed"
    exit 1
fi

echo $FRC_ROOT/libs/allwpilib
cd $FRC_ROOT/libs/allwpilib
if [ $? -ne 0 ]; then
    echo "ERROR: could not change into allwpilib directory, does it exist?"
    exit 1
fi

echo "building WPILib"
./gradlew -PmakeSim build
if [ $? -ne 0 ]; then
    echo "build failed, trying once again"
    ./gradlew -PmakeSim build
    r=$?
    if [ $r -ne 0]; then
	echo "build failed (second attempt)"
	exit $r
    fi
fi

echo "copying Gazebo plugins"
find $FRC_ROOT/libs/allwpilib/simulation/frc_gazebo_plugins/build -name *.so -type f -exec cp {} $FRC_ROOT/sim/plugins/ \;
r=$?
if [ $r -ne 0 ]; then
    echo "failed to copy Gazebo plugins"
    exit $r
fi
echo "Gazebo plugins copied in $FRC_ROOT/sim/plugins"
