#!/bin/bash
if [ -z "$1" ]; then
    echo "ERROR: you must specify the project name"
    exit 1
fi
project_name=$1

project_path=$(find $FRC_ROOT/projects -name $project_name)
if [ -z "$project_path" ]; then
    project_path=$(find $FRC_ROOT/frc_gazebo_2021/src -name $project_name)
fi
if [ -z "$project_path" ]; then
    echo "ERROR: project not found"
    exit 1
fi
cd $project_path
./gradlew simulateExternalCpp
exit $?
